#!/sbin/openrc-run

name="httpd-6"
description="tipidee for HTTP on ipv6"
_ip=::
_uid=`id -u www-data`
_gid=`id -g www-data`

command=/usr/bin/env
command_args="UID=${_uid} GID=${_gid} s6-tcpserver -U ${_ip} 80 tipideed"
command_background=yes
directory=/home/www-data
pidfile=/run/httpd-6.pid
error_log=/run/httpd-6.fifo
error_logger="logger -t httpd-6"

depend() {
	need net localmount
}

start_pre() {
	mkfifo -m 0600 /run/httpd-6.fifo || :
}
